### ISSUE TITLE
mnemonic seed derivation path

### ISSUE THREAD

**Issue by JijoBose** [DigiByte-Core/digiutility#6]
We can see that the derivation path is `m/44'/14'/0'/0`
https://github.com/DigiByte-Core/digiutility/blob/9b22fcc24af3b59be8659a5a4c53b3970d5dcac3/lib/Address.js#L22
 
 When I enter the seed mentioned in the test into the [bip39 mnemonic code](https://iancoleman.io/bip39/),  the public key for the path m/44'/14'/0'/0'/0 Isn't the same as mentioned in the test case.
 
https://github.com/DigiByte-Core/digiutility/blob/9b22fcc24af3b59be8659a5a4c53b3970d5dcac3/test/Address.test.js#L5

Could you ( @gto90 ) please guide me if I'm doing something wrong here?

**Comment by gto90** [comment]
Good evening @JijoBose ,

This repository is maintained by @digicontributer .  He should be able to guide you.
